# -*- coding: utf-8 -*-
"""naive_bayes_weather_sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xzUE3YuMce--x8I3XA7FTltxgn9Wvezk

https://www.geeksforgeeks.org/naive-bayes-classifiers/
"""

#generate a model
from sklearn.naive_bayes import GaussianNB

# Assigning features and label variables
data ={'outlooks':['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy'],
'temp':['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'],
'Humidity':['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High'],

'Windy':['False','True','False','False','False','True','True','False','False','False','True','True','False','True'],


'play':['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']}

import pandas as pd
df=pd.DataFrame(data)

df

df_c=df.astype('category')

#convert  data type object to categorical
df_c["outlooks"]=df_c["outlooks"].cat.codes
df_c["temp"]=df_c["temp"].cat.codes
df_c["Humidity"]=df_c["Humidity"].cat.codes
df_c["Windy"]=df_c["Windy"].cat.codes
df_c["play"]=df_c["play"].cat.codes

df_c

X=df_c.iloc[:,:4].values
X

y=df_c.iloc[:,4].values

y

#Create a Gaussian Classifier
model = GaussianNB()


# Train the model using the training sets
model.fit(X,y)


#Predict Output
y_pred= model.predict(X)

y

from sklearn.metrics import accuracy_score,confusion_matrix
print (accuracy_score(y,y_pred))

predicted=model.predict([[0,2,1,1]])
predicted